### ISSUE TITLE
RequestModelAction cannot handle UpdateModelAction

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/sprotty#129]
Requesting the model from the server when both client-side as server-side layouting are enabled, results in an `UpdateModelAction` rather than a `SetModelAction`. However when executing the following (from the circlegraph example in sprotty-server), the `setModel` constant waits indefinitely:

```typescript
const dispatcher = container.get<IActionDispatcher>(TYPES.IActionDispatcher);
websocket.addEventListener('open', async () => {
    const setModel = await dispatcher.request(RequestModelAction.create());
    await dispatcher.dispatch(setModel);
    await dispatcher.dispatch(new FitToScreenAction([]));
}, { once: true });
```

This is probably because only `SetModelAction` is expected while `UpdateModelAction` is also possible:

```typescript
export class RequestModelAction implements RequestAction<SetModelAction> {
   ...
```

**Comment by spoenemann** [comment]
I cannot reproduce this with the current `master` version of `sprotty-server`. Could you check again, too?

**Comment by tomvdbussche** [comment]
It seems to work correctly with the latest version of master. Look like it was fixed by https://github.com/eclipse/sprotty-server/pull/54 since it now correctly sends a set model action

**Comment by spoenemann** [comment]
Ok, thanks for confirming!
