### ISSUE TITLE
Add context menu support

### ISSUE THREAD

**Issue by planger** [eclipse/sprotty#139]
We've been working on a context menu support for GLSP and thought it might be useful to push this to Sprotty instead. What do you think?

The idea is that there is a generic `IContextMenuService` in Sprotty and depending on the context in which it is used (inside Theia, plain react app, or even Eclipse RCP) we bind a different implementation to this service that passes on the job of rendering the context menu to the "native" context menu implementation.

```typescript
export interface IContextMenuService {
    show(items: MenuItem[], anchor: Anchor, onHide?: () => void): void;
}
```

The context menu providers in Sprotty could look like below (so they specify all details about a menu item and define which Sprotty actions are going to be executed on click). To decide whether an item is enabled or not, it can use the state of the model (e.g. selection as below):

```typescript
@injectable()
export class DeleteContextMenuProvider implements IContextMenuProvider {
    getActions(root: Readonly<SModelRoot>, lastMousePosition?: Point): Promise<MenuItem[]> {
        const selectedElements = Array.from(root.index.all().filter(isSelected).filter(isDeletable));
        return Promise.resolve([
            {
                id: "delete",
                label: "Delete",
                sortString: "t",
                group: "a",
                actions: [new DeleteElementAction(selectedElements.map(e => e.id))],
                isEnabled: () => selectedElements.length > 0,
                isVisible: () => true,
                isToggled: () => false
            }
        ]);
    }
}
```

So far we've created an implementation for Theia based on Theia's context menu support (see [our work in progress implementation](https://github.com/eclipsesource/graphical-lsp/commit/fa14b76a8d6c14d7f73f08169297bb942bec0b0f#diff-0a363f67bcc2fb96de5ef8a2a5cf3fdb)). Essentially it registers the commands, menu actions, and submenus in Theia as well as a special command handler that passes on the Sprotty actions to the action dispatcher. It currently supports grouping, submenus, icons, sorting, enablement, toggle, as well as putting menu items into a parent that some other provider defines.

This is how it looks like in action:
![Peek 2019-10-31 18-16](https://user-images.githubusercontent.com/588090/67970819-eea2d780-fc0b-11e9-8fe4-215c05a5022f.gif)

Before finalizing this change, I was wondering whether I should rather put it into Sprotty first and then do the GLSP integration (so that menu items can be provided also from a server). The work in progress implementation in GLSP is here: https://github.com/eclipsesource/graphical-lsp/commit/fa14b76a8d6c14d7f73f08169297bb942bec0b0f

Please let me know what you think! I'm happy to add this to Sprotty instead of GLSP only.

Happy Halloween! ;)

**Comment by tomvdbussche** [comment]
I'd love to see this feature available in Sprotty. I have created something similar (although more basic) to provide a context menu from inside Eclipse, but having this feature in Sprotty would make things a lot easier.

**Comment by planger** [comment]
Thanks for your positive Feedback!

> I'd love to see this feature available in Sprotty. I have created something similar (although more basic) to provide a context menu from inside Eclipse, but having this feature in Sprotty would make things a lot easier.

How does your Sprotty-based editor communicate with Eclipse? Via a JSON RPC connection to a server running in the Eclipse RCP application? If yes, It would be awesome, if you could contribute the Eclipse RCP based implementation of the interface
```typescript
export interface IContextMenuService {
    show(items: MenuItem[], anchor: Anchor, onHide?: () => void): void;
}
```
e.g. by sending a message to the backend in Eclipse and then rendering the context menu at the position of the provided anchor. It would be very nice to have a support for the context menu in Theia and Eclipse RCP, both using the same interface from Sprotty.

Not sure though, where you'd be able to contribute that. We have a generic integration with Eclipse RCP for GLSP, but it hasn't been published yet (is in progress though). However, the implementation of the context menu support should actually be in Sprotty somewhere.

**Comment by tomvdbussche** [comment]
What I did was create a new action that is sent from the client to the server when right-clicking, containing all possible actions for that location. On the server side I'm using the `DiagramServerEndpoint` provided by [eclipse/sprotty-server](https://github.com/eclipse/sprotty-server) to establish a websocket connection through Jetty.

**Comment by planger** [comment]
> What I did was create a new action that is sent from the client to the server when right-clicking, containing all possible actions for that location. On the server side I'm using the `DiagramServerEndpoint` provided by [eclipse/sprotty-server](https://github.com/eclipse/sprotty-server) to establish a websocket connection through Jetty. As far as I think this does not use JSON RPC

Cool, that's what I meant. It would be great to have an implementation of the context menu service for Eclipse RCP in any case. I'm not sure where you should put it though, but I guess we'd be able to figure that out :) Ideally, we'd had a repository where we keep the Eclipse RCP integration for Sprotty, which then would be the perfect home for the context menu service too. Are you able to push a repo to Github with something like that? Thanks in advance!

**Comment by spoenemann** [comment]
Hi Philip, thanks for the proposal!

I'm currently thinking whether it would make more sense to implement such UI parts outside of Sprotty, using the ModelSource and the ActionDispatcher as means to interact with the diagram. My question is: is it necessary to have direct access to the `SModelRoot` (the _internal_ model), or would the `SModelRootSchema` (the _external_ model) provided by the ModelSource be enough? For additional information such as the current selection, we can use the new request / response actions (see e.g. [local-model-source.ts](https://github.com/eclipse/sprotty/blob/340bec62075f3db02f2bd339ef8edccbfb692811/src/model-source/local-model-source.ts#L107-L112)).

I'm not opposing the idea, but I'd like to make sure we don't introduce unnecessary complexity to the base framework.

**Comment by planger** [comment]
Hi Miro,

thanks for the feedback! I think it is good to raise the question; it has a point!

You are certainly right regarding the selection, the viewpoint, and the action dispatching. This could all easily be done outside of Sprotty.

However, I guess that context menu item providers might benefit from the internal model in some cases, e.g. to test against features of model elements (e.g. deletable). Theoretically, this could also be queried via request/response actions that are sent from outside though. I'm not sure whether it would make things simpler, but it would be doable.

The mouse listener should probably also still be registered as a Sprotty mouse listener, right? The code of the mouse listener doesn't necessarily have to live in Sprotty, though.

Are you suggesting that we rather put the entire code into the sprotty-theia integration or keep it in the applications only?

In the end, I think it also depends on how relevant the cross-platform use case for Sprotty diagrams is (that is, if we want to be able to define a Sprotty diagram once, and use it with minimal effort also in different platforms, such as Theia, Eclipse RCP, VSCode). Because if this use case is very relevant, then it imho makes sense to have a common way of defining context menus inside Sprotty and have integration code (such as sprotty-theia) that is translates those menus into the native way of rendering menu items in different platforms. If this use case is not relevant, then I guess it should be fine to have the context menu as part of the integration code to provide a framework for defining those.

Leaving context menu support entirely to the application (as opposed to the platform) might lead to code duplication though, as the code for defining menu items, rendering them on a platform, and sending actions back to the action dispatcher on-click would probably always be the same for each platform (Theia, etc.).

I think I would tend to having "Sprotty-native support" for menu items to be able to specify them as part of the Sprotty diagram; but I do get your point to avoid having to cope with menu items, registries and the like in Sprotty. So I'd understand, if you prefer to keep it out and keep menu item support outside of Sprotty (in sprotty-theia or even GLSP only).

**Comment by spoenemann** [comment]
Ok, let's include native support for context menus. We should have proper documentation of all first-class features at some point...
