### ISSUE TITLE
Deploying of artifacts from the Eclipse CI

### ISSUE THREAD

**Issue by tortmayr** [eclipse/sprotty#150]
According to the discussion on Gitter you are interested in publishing sprotty artifacts from the Eclipse CI servers. We recently did setup something similar for GLSP which allows us to publish to npm and maven (OSSRH). Here is a quick summary of the setup process:

### Prerequiste tasks for the Eclipse IT Team
The Eclipse IT team has to setup bot accounts for npm/sonatype and add the credentials to your CI instance.
For OSSRH publishing there is already an entry in the [wiki](https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F).
For npm publishing there is no entry in the wiki (yet) but you can use our [bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552833) as reference.
In a nutshell we requested the following:
- Configuration of GPG keys and OSSRH bot account
- Configuration of NPM bot account + storing auth token on Jenkins instance

### Maven publishing via Jenkins pipeline
The OSSRH publishing process is documented in the [wiki](https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F) and our take on this can be found [here](https://github.com/eclipse-glsp/glsp-server/blob/master/Jenkinsfile)

### Npm publishing via Jenkins pipeline
For npm publishing there is no documentation yet. We solved this by writing the credentials in an environmental variable and then updated the .npmrc file accordingly.
https://github.com/eclipse-glsp/glsp-client/blob/master/Jenkinsfile

**Comment by JanKoehnlein** [comment]
For the time being, it looks like the current infrastructure for sprotty's builds still works on JIRO.
But of course we'd favor a complete CI pipeline including signing and publishing, which currently happens from our servers, from Eclipse. As you have just set that up for GLSP, we'd really appreciate if you did the same for sprotty. Let us know the steps you need our help for.

**Comment by tortmayr** [comment]
The Eclipse IT Team has setup a NPM bot account so that we can publish from the Sprotty JITT:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569264

@JanKoehnlein @spoenemann Could you please invite the bot to the sprotty NPM org?  ID: eclipse-sprotty-bot

**Comment by JanKoehnlein** [comment]
There is a problem with on npmjs.org with sprotty (core) that doesn't let me add collaborators. I've contacted their support.

I have invited `eclipse-sprotty-bot` to the `sprotty` organisation on npmjs which owns all other sprotty packages.

**Comment by tortmayr** [comment]
I have setup the deployment jobs on the [Sprotty JITT](https://ci.eclipse.org/sprotty/view/Deploy/). For testing purposes I have manually triggered the deployment job for the current sprotty-theia master and was able to successfully publish the [new package](https://www.npmjs.com/package/sprotty-theia/v/0.10.0-next.f56ba71). So everything seems to work as expected.

In addition, I have opened PRs in sprotty and sprotty-theia that trigger the deployment jobs for changes on master. Before we merge these PRs the current deployment jobs running on the Typefox CI should be deactived.

**Comment by JanKoehnlein** [comment]
I'm still trying to add the sprotty package to the new sprotty org at npmjs. In the meantime, I've added the eclipse-sprotty-bot to the typefox org and a team that has write access to the sprotty package. But they have to accept the invite. Do you know who would do that?

**Comment by JanKoehnlein** [comment]
BTW, thanks a lot for your work!

**Comment by tortmayr** [comment]
I have asked in the corresponding bugzilla ticket for accepting the invites and  they have (allegedly) already accepted them: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569264#c2. It's probably best to address the problem in this ticket.
