### ISSUE TITLE
Can sprotty be run without the server?

### ISSUE THREAD

**Issue by szymoc** [eclipse/sprotty#159]
It is not immediately clear whether the building of sprotty diagrams can be done exclusively in the browser. Is is possible to define, render and serialize diagrams client side only?

**Comment by tomvdbussche** [comment]
Yes by default everything in Sprotty runs client-side only. If you build the examples using `yarn examples:build`, then navigate to the examples directory and just open the `index.html` file. Everything should work fine without having to start any kind server.
