### ISSUE TITLE
Interactivity

### ISSUE THREAD

**Issue by Baltoli** [eclipse/sprotty#192]
Apologies if this is covered somewhere in the docs / examples - I'm looking for a high-level idea of how to implement an interactive visualisation using sprotty.

* I currently have a sprotty model / graph generated by `elkjs`, which I can render nicely in the browser
* I can get mouse events on this graph and see what part of the model they reference
* Where I'm stuck is how best to mutate / update / recreate the model based on these events - for example, to replace the model element being clicked with something else.
  * Should I modify the model directly (i.e. recurse into children looking for specific data)?
  * Is this the intended use case for model matchers?

Let me know if this question is unclear - thanks for the help!

**Comment by spoenemann** [comment]
Would you like to implement this logic in the client (TypeScript) or server (Java)?

**Comment by Baltoli** [comment]
All in TypeScript - we ingest a JSON description from an external API into our app, then lay it out with elkjs and render with sprotty. We don't have a Java layout server.

**Comment by spoenemann** [comment]
I think the best approach is to write a subclass of `LocalModelSource` and implement your logic there. That class can receive user actions like selection, modify the external model accordingly and then call `updateModel()` to dispatch actions that update the internal model.

See this example:
https://github.com/TypeFox/npm-dependency-graph/blob/master/depgraph-navigator/src/browser/graph/model-source.ts

It's live at http://npm-dependencies.com/

**Comment by spoenemann** [comment]
If you prefer to separate your logic from the ModelSource, you can also implement it somewhere else, use action handlers (via `configureActionHandler`) to listen for user actions, and call `updateModel(...)` on the LocalModelSource that you get from the Inversify container.

**Comment by Baltoli** [comment]
That's very helpful - thanks again!
