### ISSUE TITLE
Moving container doesn't move routing points of edges

### ISSUE THREAD

**Issue by avshenuk** [eclipse/sprotty#193]
Pre-conditions:
1. you have a container node (node having child nodes)
2. those children have edges between them 
3. those edges have computed routing points

Expected:
When moving container node, routing points of the edges are moved too. (The same logic is applied when you move both source and target of an edge).

Speculations:
The code `src/features/move/move.ts` -> `MoveCommand.execute` looks for attached edges of the moved node only and it seems non-trivial to find the children of that node as `SModelElement` is not aware of that. So I assume you need to add a map to `SModelRoot` similar to how looking up a parent is implemented there. 
Otherwise, it seems that conceptually that can fit together with https://github.com/eclipse/sprotty/issues/161 as these cases require some special handling of container/group components.

**Comment by Darkgaja** [comment]
Hi,

I've looked into this issue and tried reproducing it. I could reproduce it under the assumption that the edge is added as a child of the graph:

https://user-images.githubusercontent.com/4377073/106620151-93c80080-6571-11eb-807d-1c71f0138cb1.mp4

However, adding the edge to the correct container results in correctly moving routing points (edd76cb):

https://user-images.githubusercontent.com/4377073/106620244-a8a49400-6571-11eb-8821-04c54500ab62.mp4

This seems to me like the intended behaviour. Maybe @spoenemann could weigh in on this?

**Comment by spoenemann** [comment]
Thanks for looking into this @Darkgaja!

@avshenuk where is the edge contained in your case? Can you confirm that it works when you make it a child of the container?

**Comment by avshenuk** [comment]
Thanks for the great investigation, guys!

Yes, you're absolutely right that in our case the edges are simply added to the root graph and not to the container itself. Didn't realise that was necessary and that would've required some computation of a common ancestor for the connected nodes as we generate the edges on the fly.

Anyway, please feel free to close this issue and thanks a lot for spending your time on this.
