### ISSUE TITLE
Cannot move diagram in Firefox

### ISSUE THREAD

**Issue by andreasjakobik** [eclipse/sprotty#195]
Hi,

I'm running the [Yangster extension](https://open-vsx.org/extension/typefox/yang-vscode) in Theia. When opening a diagram it renders just fine but moving the diagram is not possible. I try to move by clicking on the diagram and then move the mouse.

Works in Chrome but not using:

Firefox browser 82.0.2 (64-bit )
Windows 10 Enterprise version 1809

Thanks,
Andreas

**Comment by JanKoehnlein** [comment]
I tried in Gitpod (Windows, Firefox) and I observed the following:
- dragging to pan works almost everywhere
- it doesn't work if you start on the label of an unselected node. The second time it works.

Is that what you observe?

**Comment by andreasjakobik** [comment]
Yes, if I make sure to select a node representing a list/container (class) or a leaf/leaf-list (attribute) therin, then dragging indeed works! 

Compared to Chrome, I still cannot drag when pointing to the module area (the "empty" space between the classes surrounded by a larger box). 

Now that I got dragging to work by selecting the right node, it is totally fine. 

Thanks!
