### ISSUE TITLE
Line jumps to visually clarify intersecting lines

### ISSUE THREAD

**Issue by planger** [eclipse/sprotty#208]
We'd like to add support for "line jumps" or "bridges" in order to guide the users' eye in following intersecting edges, as e.g. below:

![image](https://user-images.githubusercontent.com/588090/109037136-ac3bbe80-76ca-11eb-92cf-7671d4ab312b.png)

I'm wondering what would be the best way of implementing them in Sprotty, as an implementation for such line jumps would require awareness of the routes of all edges in a diagram.

Typically, for each `SRoutableElement` a `RoutableView` is invoked one after the other, which in turn runs the `IEdgeRouter` to obtain routes. These routes are then translated into a SVG path by the view. The routes of other edges, however, are not explicitly persistent or available to others during a rendering pass of the entire diagram, neither for the views nor the router. There would have to be a rendering context that is renewed for each rendering pass and that collects the routes of all edges rendered so far so that we could integrate a detection for intersections and subsequently rendering jumps for them. Also, it'd be nice to have these line jumps independently from the actual routers, as those jumps are not necessarily tied to the behavior of a router.

So another way could be to add a `IVNodePostprocessor`, which could pass through edges and find intersections and replace them with those line jumps. This would be nice because it would be independent of the actual router or even views (to some extent), however it would have to run the registered routers again for the model elements to compute their routes, which is inefficient, and then it would have to fiddle around with the path on SVG level, which seems a bit off too.

@spoenemann What do you think would be the best approach? Thanks a lot for your thoughts on that!

**Comment by planger** [comment]
Right, good idea!

We could annotate the `vnode` with the segments via `svgPath.data.attachData`, react in a post processor to the graph root element and then run through all the edge segments to find intersections and then manipulate their SVG path. That could work... I'll give it a try in the next few days.

Thanks!

**Comment by spoenemann** [comment]
Another approach: the `renderChildren` method has an optional `args` parameter:

https://github.com/eclipse/sprotty/blob/4ff859071e2b32ed94e031a973246037e71992ee/src/base/views/viewer.tsx#L79

The parent view that contains connections could pre-compute all routes and pass them as `args` so the contained connections can reuse that data. Then the connection views could include the "jumps" themselves when rendering. This approach would require only a few utility functions (pre-compute routes, render hops).

**Comment by planger** [comment]
That sounds even better, thanks!
It'll make it easier to render the hops in the views (instead of having to manipulate the SVG after the fact).

**Comment by spoenemann** [comment]
There's another use case that could benefit from this: some kinds of diagrams like data flow diagrams and circuit schematics use "junction points" to highlight where multiple connections run together. So it's kind of the opposite of the "jumps" that you are targeting, but computing junctions also requires the routes. It would be great if the added infrastructure could be generic enough to cover both use cases.

**Comment by planger** [comment]
Hm, right, that could indeed be another use case. In a similar diagram style that we implemented in the past, we explicitly modeled those junction points as "free floating ports" in the GModel, but I guess they could be also represented by implicit intersections of edges, which could then be highlighted differently but with the same infrastructure as we would render jumps.

I also have another somewhat related future use case in mind, which is an obstacle-aware routing algorithm (such as the one from adaptagrams/libavoid), which needs to compute all routes at once too to minimize intersections and avoid overlaps. With the approach of computing routes the way we do it today, this would be unnatural, but with allowing to compute the routes in one pass and hand them over in the arguments, such routing algorithms could be more easily integrated.

**Comment by planger** [comment]
Finally, I got to work a bit on this issue and have a first prototype. I'll share the code within the next couple of days. Here is how it looks like (intersections are indicated in the gif below by a red circle):
![intersection-detection](https://user-images.githubusercontent.com/588090/122257044-e924fe80-cecf-11eb-8248-781e51722c8c.gif)

I use an enhanced version of https://github.com/rowanwins/sweepline-intersections (MIT). I had to change it in a few parts though to allow reporting the edge IDs and segment indizes as well. As it is MIT, I think we could further harmonize this enhancement of that library with the Sprotty types and even include it in Sprotty.

**Comment by pcdavid** [comment]
FWIW, last year we added support for a new kind of "Jump Links" in GMF Runtime for rendering these intersections. Instead of rendering a semi-circle at the intersection, it simply creates a "gap" in the edge. See https://projects.eclipse.org/projects/modeling.sirius/releases/6.3.1 for a screenshot of what it looks like.

The result can be cleaner visually (IMO) on large diagrams with many intersections.

**Comment by planger** [comment]
> FWIW, last year we added support for a new kind of "Jump Links" in GMF Runtime for rendering these intersections. Instead of rendering a semi-circle at the intersection, it simply creates a "gap" in the edge. See https://projects.eclipse.org/projects/modeling.sirius/releases/6.3.1 for a screenshot of what it looks like.
> 
> The result can be cleaner visually (IMO) on large diagrams with many intersections.

Thanks for the feedback! Sure that's also an option.

The [proposed implementation](https://github.com/eclipse/sprotty/pull/226) already renders a small gap for the line that doesn't "jump" to avoid actually crossing it (see [gif](https://user-images.githubusercontent.com/588090/124655075-a4bdca80-de9f-11eb-9be6-e8dfd2da8f27.gif)). If you'd want gaps only, we could easily provide an alternative view implementation that renders no jumps and but just a centered gap (see `JumpingPolylineEdgeView` of my [PR](https://github.com/eclipse/sprotty/pull/226)).
