### ISSUE TITLE
Refresh container dimension

### ISSUE THREAD

**Issue by euskalhenriko** [eclipse/sprotty#220]
Hi, i'm using sprotty in client side to draw a dataflow.
Everthing works well, but I have problems using the `FitToScreen` action.
I need to change the dimension of sprotty div container programmatically (for example to show an info div) and after it, i will fit and center the diagram, so after showing the div, I use this code (I don't want animation): 
`actionDispatcher.dispatch(new FitToScreenAction([], 10, undefined, false));`
The diagram is fitted and centered, but using the original dimension of div, not the new one.
I try different ways to change the dimension: the div is absolute positioned
```
#sprotty
      position absolute
      top 0
      left 0
      right 0
      bottom 0
      svg
        width 100%
        height 100%
```
And when the other div is shown, I try changing the `right` attribute to '300px' and modifying the width using js
```
document.getElementById('sprotty').style.width = 'calc(100% - 300px)';
```
Both change correctly the div but the fit seems don't update the bounds.

Any tip?
Thank for help

**Comment by spoenemann** [comment]
Sprotty needs to know the canvas bounds so the viewport operations work correctly. Probably you need to something like this:

https://github.com/eclipse/sprotty/blob/0e060519651a0ece1689e416455a9676f3147a71/src/base/views/viewer.tsx#L188-L194

**Comment by euskalhenriko** [comment]
Thank you, it works.
