### ISSUE TITLE
Node.js support and restructuring to monorepo

### ISSUE THREAD

**Issue by spoenemann** [eclipse/sprotty#243]
I am seeing increasing demand for a Node.js backend for Sprotty. I already created an example for that about a year ago:

https://github.com/spoenemann/theia-sprotty-nodejs-example/blob/master/diagram-view/src/node/diagram-server-impl.ts

I would like to share this to the Sprotty project as a separate package. At the same time, I propose to change this repository to a monorepo with multiple packages:

 * `sprotty`
 * `sprotty-elk` (moved from [eclipse/sprotty-layout](https://github.com/eclipse/sprotty-layout))
 * `sprotty-node` (new)
 * `sprotty-protocol` (new)

This will make it considerably easier to keep the code synchronized and to implement cross-package functionality.

I'd leave `sprotty-theia` and `sprotty-vscode` separate because their dependency tree is more complex, and I have previously seen problems when trying to include both the Theia and the VS Code integration in the same Yarn workspace. I would also keep `sprotty-server` separate to avoid a mixed-platform repository (TypeScript / Java).

`sprotty-node` should not have a dependency to `sprotty` to avoid using browser code in a Node.js context. For that reason, we need to extract common data structures into a new package `sprotty-protocol`. This is also a good opportunity to isolate and document the client / server protocol of Sprotty more clearly. For now that new repository should contain

 * SModel (schema) declarations
 * Actions (#233)

In order to keep API breakage at a minimum, we could mark the original declarations in the `sprotty` package as deprecated (they will still work, but should be changed to the new `sprotty-protocol` definitions at the earliest convenience).

What do you think?

**Comment by tortmayr** [comment]
:+1: 
We are currently also evaluating the efforts of providing a node.js based GLSP server so this sounds like the perfect opportunity to align our efforts. 

In GLSP we are already using a monorepo pattern similar to your suggestion and are quite happy with it. So I'm all for it. Keeping the core sprotty code and application specific glue code in separate repositories definitely makes sense. We also came to the same conclusion.

>In order to keep API breakage at a minimum, we could mark the original declarations in the sprotty package as deprecated (they will still work, but should be changed to the new sprotty-protocol definitions at the earliest convenience).

Sounds good to me. However, I would only provide the deprecated API for limited time frame and the drop the support for it in a later release (similar to how it has been done in Theia with the @theia/languages  AP). In our case I think we should drop the deprecated API once sprotty is leaving incubation.

**Comment by spoenemann** [comment]
Ok, I added a release v0.11.0 and scheduled it for 11/11 😂

I'll do the restructuring after v0.10.0 is released. Let's aim to include as many of the necessary API-breaking changes as possible in v0.11.0 so we can mark parts of the API as deprecated in that version and drop them in v1.0.0.

I'm currently unsure whether we really need two separate packages `sprotty-node` and `sprotty-protocol` because I don't think we really need to use Node.js API in the backend part of the Sprotty framework. That part should be independent of the actual communication channel. In some projects the client-server communication might be via a websocket, while in VS Code extensions we would use the webview message API provided by VS Code.

I recently set up a project using Sprotty in a VS Code extension:
https://github.com/litanlitudan/mlir-hlo-sprotty-vscode
The diagram implementation is just a placeholder, it's not done yet. But in `src/sprotty-node` you can find the code that I envision for the new `sprotty-protocol` package. It's not self-contained yet, we would need to move more code from the `sprotty` base package to avoid references to it (the dependency is in the other direction).

Initially I thought about putting `diagram-server.ts` and related stuff into a separate package `sprotty-node`, but since it doesn't use any Node.js API, I'd rather include it in `sprotty-protocol` as mentioned above. WDYT?
