### ISSUE TITLE
How to bind custom action to events

### ISSUE THREAD

**Issue by euskalhenriko** [eclipse/sprotty#26]
Hi, i recover this issue from theia-ide/sprotty repository: https://github.com/theia-ide/sprotty/issues/240
My problem is a bit different: I have a Vue (not using TypeScript) project using sprotty to draw an Elk generated graph.
I have found various example to configure and use Sprotty but all use TypeScript, so, I used the Elk Graph Viewer sample to implement a "bridge" library in TypeScript that configure Sprotty and then I use it in Vue project, and it work well.
I have been able to implement the issue solution (implementing `IActionHandler`) in this "library" but I cannot figure how to "send" the action content back to the Vue project, or how to configure a custom function to handle the event from Vue project. Basically I only need the id of selected node(s)
Is it possible? There is some example for this?
Thank you very much for any help

**Comment by spoenemann** [comment]
You can register an action handler to listen for specific action kinds, e.g. selection. You can do whatever you like inside the action handler implementation.

**Comment by euskalhenriko** [comment]
Thank Miro, I could do it with pure javascript finally
