### ISSUE TITLE
Setup nightly deployment for new mono repo

### ISSUE THREAD

**Issue by tortmayr** [eclipse/sprotty#261]
With the migration to a mono repository the nightly deployment job for the sprotty repository is not working anymore.
The configuration needs to  be updated and the Eclipse Sprotty Bot needs to be added to the new npm packages (i.e. sprotty-protocol) as maintainer. NPM recently also introduced dedicated automation tokens for CI jobs that are more secure than classical access tokens so we should use them instead.

For this some changes in the npm settings of the following packages are required:
- sprotty
- sprotty-elk
- sprotty-protocol
Optional also:
- sprotty-theia
- sprotty-vscode
- sprotty-vscode-webview

@spoenemann I don't know your policy here. You could either add me as maintainer for these packages so that I can do the necessary changes myself or I would have to ping you a couple of times and request the changes. Both is fine for me.

**Comment by spoenemann** [comment]
I can add you to the packages. What's your npm user name?

**Comment by tortmayr** [comment]
Thanks,
username: tortmayr (https://www.npmjs.com/~tortmayr)

**Comment by spoenemann** [comment]
I added you to the sprotty npm team.

**Comment by tortmayr** [comment]
Nightly deployment for sprotty-protocol & sprotty-elk works on my test branch. However, the deployment for the "sprotty" core package does not work due to invalid credentials.  I don't have the necessary permissions to change settings of the sprotty package (probably because it was originally published under the typefox org?).

@spoenemann  Could you please check if the eclipse-sprotty-bot as write access to the "sprotty" package?

**Comment by tortmayr** [comment]
Yes thanks. Now everything works like a charm
