### ISSUE TITLE
What is the policy in regards to updating copyright headers?

### ISSUE THREAD

**Issue by tortmayr** [eclipse/sprotty#279]
@spoenemann I was wondering what sprotty's policy/recommendation in regards to updating copyright headers (in particular the year range) is?
By quickly scanning through the code base I could discover some files which seem to use an updated year range (e.g.  `Copyright (c) 2017-2018 TypeFox and others.`)  while others just use the inception year and the header is not updated for follow-up changes.

So what is the expectation here? Should we aim at keeping the year range up to date or should we not touch the original copyright header at all?

**Comment by spoenemann** [comment]
Hi! My approach so far was to avoid updating the year in most cases, as that would pollute the version history of every file. I did update the year range in some specific cases, like when I moved code to other locations or changed large parts of the code. But I don't have a clear criterion for that. I'm open to suggestions as well as recommendations from the Eclipse Foundation.

**Comment by tortmayr** [comment]
I'm not aware of any recommendations from the Eclipse Foundation.
In GLSP we typically check the header when we make changes to the file and update the year if necessary.
However, I don't have a strong opinion on that and not updating the year in most cases is fine for me.
