### ISSUE TITLE
ButtonHandler API does not work with injection

### ISSUE THREAD

**Issue by tortmayr** [eclipse/sprotty#300]
It looks like with the current implementation of the `IButtonHandler` resp. the `ButtonHandlerRegistry` its not possible to create Button handlers that use injected properties. The `ButtonHandlerRegistry` is directly creating new handler instances using the new keyword hence injected values are not set.

We should probably use real inversify factory injection here (https://github.com/inversify/InversifyJS/blob/master/wiki/factory_injection.md). 

@spoenemann Can we easily change this or is there a specific reason that forces us to use currently implemented approach?

**Comment by spoenemann** [comment]
I think we can just change it and make it consistent with other features. Let's take the LayoutRegistry as example:

https://github.com/eclipse/sprotty/blob/c7368c500cd2498757a1796a98afb2e94129bb36/packages/sprotty/src/features/bounds/layout.ts#L27-L47
