### ISSUE TITLE
SourceAnchor and TargetAnchor is lost after routing?

### ISSUE THREAD

**Issue by rsoika** [eclipse/sprotty#315]
I try to implement a new `ManhattanEdgeRouter` for my [BPMN Modeler](https://github.com/imixs/open-bpmn/) based on GLSP.
For BPMN it is important to include the Source and Target Anchor points in the RoutingPoint List (called WayPoints in BPMN).
When I debug the `route()` method of the `ManhattanEdgeRouter` (which I currently try to extend) I can see that these routing points are included as a result of this method, which is fine.

But at the end of the day when the GLSP Framework sends a `ChangeRoutingPointsOperation` event to my server, the source and target routing points are missing.

I invested hours and hours now to figure out when this happens but without success. 
@spoenemann can you please answer me the question if in the Sprotty Routing implementation is a peace of code which removes these two routing points? If not, than I will go back to the GLSP team to find the issue there. But for the moment it is not clear to me where my two routing points get lost.

**Comment by spoenemann** [comment]
Hard to say without debugging in detail, especially because I did not implement ManhattanEdgeRouter. In general, the source and target anchors are not listed explicitly in the model, but computed on demand. I don't know what the ChangeRoutingPointsOperation does, so I can't tell what's the problem.

**Comment by rsoika** [comment]
Thanks for your response. It seems it is in deed a GLSP issue and not a Sprotty Issue. 
We have a lengthy [discussion](https://github.com/eclipse-glsp/glsp/discussions/767) about my problem and I think the solution is now on the way.
