### ISSUE TITLE
Support a command palette to quickly invoke actions

### ISSUE THREAD

**Issue by planger** [eclipse/sprotty#34]
With https://github.com/eclipsesource/graphical-lsp/pull/136 we proposed a command palette for GLSP. In GLSP we will fill this command palette with editing actions that come from the server (similar to code completion in LSP). However the base is independent of that as it obtains all available actions from a dedicated DI-configurable action provider.

Is that something that you would welcome in Sprotty as well? If yes, we could extract the GLSP-independent part and move this to sprotty.

Here a short screen cast how the initial implementation looks like:
![command-palette-demo](https://user-images.githubusercontent.com/588090/51084998-4b8fd880-1733-11e9-8b9f-75f0374444c4.gif)

**Comment by JanKoehnlein** [comment]
Looks interesting. How about the UI? Would it make sense to leave that to the surrounding app, e.g. Theia? How is it triggered? Wouldn't one expect a graphical palette?

**Comment by planger** [comment]
Thanks for the feedback!

> Wouldn't one expect a graphical palette?

Yes, a "classical" graphical palette is currently under development and should arrive soon. We are happy to also contribute this classical palette to Sprotty, once it's finished.

The command palette proposed here is meant to be orthogonal to the classical palette, as a keyboard-oriented and -- if there is a element selection -- context sensitive way of invoking actions, similar to a Code Completion / IntelliSense / Quick-Fix functionality for code. In the example above, we just added select commands for demonstration, but essentially any commands can be executed... in our implementation, an action provider just needs to provide a set of `LabeledAction`s for a context (currently only the current selection). A `LabeledAction` is essentially a label to be shown in the list and an array of Sprotty `Action`s to be dispatched on invocation.

>  How about the UI? Would it make sense to leave that to the surrounding app, e.g. Theia? How is it triggered?

In our current implementation, the UI is drawn by a [CommandPalette](https://github.com/eclipsesource/graphical-lsp/blob/master/client/packages/glsp-sprotty/src/features/command-palette/command-palette.ts#L69) class that is instantiated via DI and invoked by a [keylistener](https://github.com/eclipsesource/graphical-lsp/blob/master/client/packages/glsp-sprotty/src/features/command-palette/command-palette.ts#L29) on <kbd>Ctrl</kbd> + <kbd>Space</kbd>. If there is no selection or multi-selection, it shows up in the left-upper corner of the base div's `_sprotty` element. If there is a single selection, it is shown on top of the selected element.

I think in most of the use cases, it should be fine that Sprotty itself handles the command palette UI, similar to Monaco handling the code completion UI itself. But, it is certainly a good idea to allow the delegation of the UI. For such use cases, we could inject an alternative implementation of `CommandPalette` that delegates the UI to e.g. Theia and its quick find component. Would you agree?

Thanks!

**Comment by spoenemann** [comment]
> I think in most of the use cases, it should be fine that Sprotty itself handles the command palette UI, similar to Monaco handling the code completion UI itself. But, it is certainly a good idea to allow the delegation of the UI. For such use cases, we could inject an alternative implementation of CommandPalette that delegates the UI to e.g. Theia and its quick find component. Would you agree?

Sounds good to me.

**Comment by planger** [comment]
Thanks for the feedback and sorry for the delay! We are currently thinking about generalizing the base of the command palette implementation to also cater for normal "graphical" palettes in terms of managing HTML divs that are rendered at specific positions and that can invoke Sprotty actions. Therefore, I wanted to wait and see how that progresses before opening a PR.

If you prefer I can already open a PR with the current implementation for command palettes, but if there is no urgency on your side, it might pay off to wait and see whether the generalization endeavor succeeds and whether it is useful for Sprotty in general.

Please let me know what you think! Thanks!
