### ISSUE TITLE
dblclick is not a WheelEvent

### ISSUE THREAD

**Issue by manfred4** [eclipse/sprotty#57]
As can be seen [https://developer.mozilla.org/en-US/docs/Web/Events/dblclick](here), the double click event 'dblclick' is a MouseEvent and not a WheelEvent, but it is typed as a WheelEvent at least [here](https://github.com/eclipse/sprotty/blob/a4ea7d804e82c53ad466f551542f5d61f708dac0/src/base/views/mouse-tool.ts#L120), [here](https://github.com/eclipse/sprotty/blob/a4ea7d804e82c53ad466f551542f5d61f708dac0/src/base/views/mouse-tool.ts#L193), [here](https://github.com/eclipse/sprotty/blob/a4ea7d804e82c53ad466f551542f5d61f708dac0/src/features/open/open.ts#L30) and [here](https://github.com/eclipse/sprotty/blob/a4ea7d804e82c53ad466f551542f5d61f708dac0/src/features/edit/edit-label.ts#L39).
This is a minor problem, as it can be cast to the correct type when used.

**Comment by JanKoehnlein** [comment]
Would you like to provide a PR?

**Comment by manfred4** [comment]
Just tried GitPod for the first time for this pull request. Works like a charm!

**Comment by JanKoehnlein** [comment]
Fixed with https://github.com/eclipse/sprotty/pull/66
