### ISSUE TITLE
Allow moving nodes in Firefox without mouse-up-event first

### ISSUE THREAD

**Issue by tomcola72** [eclipse/sprotty#72]
In Firefox-Browser to move a node, you have to select a node first, then mouse-up, then you're able to move the node.

**Comment by tomcola72** [comment]
Potential fix:

In MoveMouseListener (move.ts - line 465):
Instead of 'mouseEnter' - 'mouseLeave' and 
instead of 'event.buttons === 0' - 'event.buttons === 1'?

Now:
`mouseEnter(target: SModelElement, event: MouseEvent): Action[] {
        if (target instanceof SModelRoot && event.buttons === 0)
            this.mouseUp(target, event);
        return [];
    }`

Fix:
`mouseLeave(target: SModelElement, event: MouseEvent): Action[] {
        if (target instanceof SModelRoot && event.buttons === 1)
            this.mouseUp(target, event);
        return [];
    }`

If you select an SModelElement in your graph, Firefox fires a mouseEnter-event. But the target is of type SModelRoot and event.buttons === 0, so mouseUp-event is triggered.

Thank you very much for your great work - Theia, sprotty, xText...!!

Tom

**Comment by spoenemann** [comment]
> Thank you very much for your great work - Theia, sprotty, xText...!!

Thanks. :-)

Unfortunately I have to move this to the next version v0.8.0 :-/

**Comment by Darkgaja** [comment]
@spoenemann I think that this one was fixed by #203 as well. You can probably close it now.
