### ISSUE TITLE
Sprotty Example

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse/sprotty#75]
Hi @JanKoehnlein @spoenemann,

I'm looking into using sprotty within theia in order to create a small demo to visualise a git repository. I don't necessarily need a language server aspect as I can mock most of the data if required. Do you have any thoughts or pointers on how to get started to use it within theia?

I tried to follow documentation, examples but it wasn't always straight forward or up to date so any help is greatly appreciated.

Thanks!

**Comment by spoenemann** [comment]
The npm dependency graph viewer has a Theia integration without language server:

https://github.com/TypeFox/npm-dependency-graph

The code is a bit outdated. I'm going to update it in a few weeks or so.

**Comment by spoenemann** [comment]
Updating and extending the documentation is also on my list. I'm not sure when I'll have time for that.

**Comment by vince-fugnitto** [comment]
Thank you for your help @spoenemann ! I'm looking forward to being able to use it 😃

**Comment by vince-fugnitto** [comment]
I just wanted to follow up on my earlier question, do you have a timeline regarding the updates to sprotty and the examples? I'm eager to be able to use Sprotty in Theia and create my own visualizations. Any help is of course greatly appreciated :)
 
@spoenemann @JanKoehnlein

**Comment by spoenemann** [comment]
I'll take some time to update the npm-dependency-graph example next week.

**Comment by spoenemann** [comment]
Sorry, I need to postpone this by another few weeks :-(

**Comment by spoenemann** [comment]
https://github.com/TypeFox/npm-dependency-graph/issues/3

**Comment by spoenemann** [comment]
The npm-dependency-graph example is updated.
