### ISSUE TITLE
Add user interface for label editing

### ISSUE THREAD

**Issue by planger** [eclipse/sprotty#83]
For use cases of Sprotty that support editing, it would be nice to also have a UI allowing the user to conveniently edit labels directly in the diagram. I've created an initial implementation that adds a new `labelEditUiModule` which reacts to the existing `EditLabelAction` and then provides a UI based on the `UIExtension` introduced in Sprotty a while ago. When the user confirms the edit, it sends out a `ApplyLabelEditAction` which can then be processed according to the specific use case. In GLSP we would forward it to the server in order to apply the modification, or you could have a local command just applying it to the `SModel`, or be forwarded to the textual language server.

![direct-edit-ui](https://user-images.githubusercontent.com/588090/56823341-df556280-6853-11e9-8c2c-b2fac1a66209.gif)

Are you, in general, interested to have that in Sprotty directly? As it doesn't put any restrictions on how the label edit is actually be applied (on a server or local), the implementation is rather agnostic of the use case.
The implementation is not perfect yet, but I guess it wouldn't be too much work to brush up the code for Sprotty.

Please let me know what you think.

**Comment by spoenemann** [comment]
Looks good! Yes, I think it makes sense to have the general UI in Sprotty and be able to implement the actual model change in the specific application.

You introduced the Nameable interface some months ago. Could that be used to define a default command for the ApplyLabelEditAction?

**Comment by planger** [comment]
Thanks for the feedback! I'll then go ahead and prepare a PR on that.

> You introduced the Nameable interface some months ago. Could that be used to define a default command for the ApplyLabelEditAction?

Yeah, good idea!

In my initial implementation I directly worked with `EditableLabel`. The `EditLabelAction` is sent out on double-click on an `EditableLabel` (that's already in Sprotty). Then I'd obtain the bounds of the element with the `editableLabel.id` using the introduced `getAbsoluteClientBounds(...)` to compute the bounds for the `UIExtension`. On <kbd>Enter</kbd>, the `ApplyLabelEditAction` is sent out with a label ID. The obvious default command would now just check whether the editable label is an SLabel and apply the new label to `SLabel.text`.

To pick up your idea, a generic command could now instead:
1. `findParentByFeature(editableLabel.id, Nameable)` and set the name of the returned nameable element. This entails a slight risk/limitation that the nameable element must be a direct parent of the editable label (or they are the same element) and you could create an implicit ambiguity by having two editable labels as children of a single nameable element.
2. The editable label has an explicit reference to the nameable element, which indicates the element to be changed by the `ApplyLabelEditAction`. This would be more explicit (removing the implicit ambiguity) and would remove the limitations regarding the element hierarchy at the cost of having to specify an additional reference.

Or we combine both approaches (check if nameable reference is set -- ie option 2 -- first, if undefined go for option 1. If undefined again eventually fallback to checking whether the element with the editableLabel.id is an `SLabel` and directly write to the `SLabel.text` property.

What do you think? Thanks for your feedback in advance!

**Comment by spoenemann** [comment]
I think option 1 is ok. For use cases where that doesn't work (e.g. edges with multiple labels), you need an application-specific action handler / command anyway. The Nameable feature should be used where there's no ambiguity.
