### ISSUE TITLE
[arch] reading SModel from the outside

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/sprotty#85]
When using sprotty in an UI framework like Theia, some user interactions are triggered outside of the sprotty architecture, e.g. keystrokes or drag and drop. You sometimes need to access certain properties of the SModel in order to turn these into sprotty actions, e.g.

- transform a screen position into a diagram coordinate (needs Viewport)
- access the selection

While within sprotty, event listeners can access the SModel, these external listeners can't.

For other cases, such as bounds, we often process certain action in the model source and keep the external model updated. External listeners can then get the current values from the model source. Unfortunately, this doesn't seem to be a viable solution for viewport actions such as `center`, as the necessary calculations and the update of the viewport happen directly in the respective command.

As a second solution, on can implement some kind of pre-action and a pre-command that gathers the necessary information and issues the real action. This sounds a bit complicated, but is safer as we don't make assumptions which actions change the needed properties.

A third solution would be to implement services, like a selection or viewport provider, that get the values directly from the current model in the command stack. This kind of breaks the encapsulation we had.

**Comment by Xupransh** [comment]
Is there a suggested method to hand off ids of SModelElements that are selected to the model-source? As of right now I can't think of anything that doesn't require a change in the architecture.

**Comment by JanKoehnlein** [comment]
Well, the model source provides the external `SModel` (aka `SModelSchema`), and it can listen to `SelectAction`s so this _can_ be implemented already. It's just a bit tedious, so this ticket is about adding the right kind of API to make it easier without breaking the architecture

**Comment by Xupransh** [comment]
Sorry I realize that the question was a little vague - So the external button would dispatch an action without any target element IDs and the modelsource would somehow figure out elements ids that are already selected (eg maintain an array of currently selected elements)?

**Comment by JanKoehnlein** [comment]
Yes, that's one solution. As an `ActionHandler`, the `ModelSource` can convert the button action into another that has the selected IDs.

**Comment by Xupransh** [comment]
I used this implementation but I see the issue with it - It becomes tedious to handle undo redo actions. 

> While within sprotty, event listeners can access the SModel, these external listeners can't.

Shouldn't the viewer be responsible for providing external buttons with information from `SModelElements`? I think there is currently no way to have information about (eg in my case, all selected elements) be provided by the viewer to an external button when the action is dispatched, but can't this be done by extending the `MouseTool` class?

**Comment by spoenemann** [comment]
> Shouldn't the viewer be responsible for providing external buttons with information from SModelElements?

Buttons are only a special case for such interaction. We should also have a solution for drag-and-drop interaction, keystrokes captured by the surrounding application etc.

> or it could be done using MobX

Yes, we should have a closer look at that.
https://mobx.js.org
