### ISSUE TITLE
[ux] add support for aligning nodes

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/sprotty#86]
Currently, you can move nodes and routing points to every position in the diagram. This results in a very smooth UX, but makes it hard to align nodes with each other.

We should add an infrastructure to help aligning nodes to some magnetic positions, be it based on other nodes or a grid.

**Comment by tortmayr** [comment]
@spoenemann I think this can be closed right?. The `ISnapper` API should provide the requested feature
