### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/sprotty#91]
When running the examples, I am unable to use the keyboard shortcuts (only CTRL+A seems to work). This does seems to work for the examples hosted online.

**Comment by spoenemann** [comment]
What operating system and browser are you using?

**Comment by tomvdbussche** [comment]
Tested with both Firefox 67 and Chromium 73 running on Fedora 30.

**Comment by tomvdbussche** [comment]
It looks like the keyboard shortcuts are working while also holding down <kbd>SHIFT</kbd> as well. I'm not sure if this is intentional, but that seems to be what is causing the issue.

**Comment by JanKoehnlein** [comment]
We changed that and forgot to update the docs.

**Comment by JanKoehnlein** [comment]
Updated the docs in the Wiki
