### ISSUE TITLE
Class Diagram top/bottom example

### ISSUE THREAD

**Issue by DamianRivas** [eclipse/sprotty#92]
Hi,

I'm a new engineer for the OpenCAESAR project at NASA's JPL. I've been trying to learn how sprotty works and admittedly it's been difficult since there doesn't appear to be a lot of documentation.

How exactly should we add labels similar to the top/bottom labels in the Class Diagram example? I looked at the source and it seems like they're implemented directly in some sort of schema, but why is it done this way?
```typescript
<SLabelSchema> {
    id: 'edge1_label_bottom',
    type: 'label:text',
    text: 'bottom',
    edgePlacement:  {
        position: 0,
        side: 'bottom',
    }
},
```
What if we want different text to render based on certain conditions? Should I be extending the SLabelView?

We created our own LSP with Xtext. Below is a piece of our DiagramGenerator, and the `subtext` child for the `edge` below is what I'm trying to render right next to the origin of the edge.
```xtend
	protected dispatch def void addToDiagram(ReifiedRelationship relationship, SGraph diagram) {
		if (relationship.source === null || relationship.target === null) {
			return
		}
		
		postProcesses.add([
			var source = semantic2diagram.get(relationship.source)
			if (source === null) {
				relationship.source.addToDiagram(diagram)
				source = semantic2diagram.get(relationship.source)
			}
			
			var target = semantic2diagram.get(relationship.target)
			if (target === null) {
				relationship.target.addToDiagram(diagram)
				target = semantic2diagram.get(relationship.target)
			}

			val id = relationship.getLocalName(resource)
			val edge = newEdge(source, target, id, "augments") => [
				children += newSElement(SLabel, id + '-label', 'text') => [
					text = id
				]
				if (relationship.inverseFunctional) {
					children += newSElement(SLabel, 'oml-invFunc', 'subtext') => [
						text = "[0,1]"
					]
				}
			]
			semantic2diagram.get(resource.contents.head).children += edge
			trace(edge, relationship)
		])
	}
```

**Comment by DamianRivas** [comment]
Essentially, all I'm trying to do is move the `[0,1]` to the location pictured here: https://i.imgur.com/lEBQd6h.png

I've logged the SLabel object to the console and saw its `position` property. At what point does this get calculated? I've investigated `SLabel` and `SLabelSchema` and neither seem to be the place to do manipulate this.

Also, out of curiosity, what is the alignment property for?
```typescript
alignment: Point = ORIGIN_POINT;
```

**Comment by DamianRivas** [comment]
I think I discovered where to do it, but I don't think the version of sprotty we are using supports it. I discovered the `edgePlacement` property in the example project...
```typescript
export class SLabel extends SShapeElement implements Selectable, Alignable, Fadeable {
    text: string;
    selected: boolean = false;
    alignment: Point = ORIGIN_POINT;
    opacity = 1;
    edgePlacement?: EdgePlacement;

    hasFeature(feature: symbol) {
        return feature === boundsFeature || feature === alignFeature || feature === fadeFeature || feature === layoutableChildFeature || feature === edgeLayoutFeature;
    }
}
```
but I don't see it in our version which is `sprotty@0.1.2` according to the yarn.lock file.
```typescript
export class SLabel extends SShapeElement implements Selectable, Alignable, Fadeable {
    text: string;
    selected: boolean = false;
    alignment: Point = ORIGIN_POINT;
    opacity = 1;

    hasFeature(feature: symbol) {
        return feature === boundsFeature || feature === alignFeature || feature === fadeFeature || feature === layoutableChildFeature;
    }
}
```
I tried doing a simple `yarn add sprotty@latest` to our theia app but that introduced some errors...

**Comment by spoenemann** [comment]
> I've been trying to learn how sprotty works and admittedly it's been difficult since there doesn't appear to be a lot of documentation.

Yes, that's on my agenda.

> How exactly should we add labels similar to the top/bottom labels in the Class Diagram example? I looked at the source and it seems like they're implemented directly in some sort of schema, but why is it done this way?

The example models are hard-coded.

> What if we want different text to render based on certain conditions? Should I be extending the SLabelView?

You can generate the text in the DiagramGenerator, so make sure those conditions are available there.

> I've logged the SLabel object to the console and saw its position property. At what point does this get calculated?

They are computed in the Sprotty client by `HiddenBoundsUpdater` and `EdgeLayoutDecorator`. The client-side layout is controlled via properties in the model, e.g. `edgePlacement` as you have seen in the example.

> Also, out of curiosity, what is the alignment property for?

See the comment of the `Alignable` interface:
_Used to adjust elements whose bounding box is not at the origin, e.g. labels, or pre-rendered SVG figures._

> I think I discovered where to do it, but I don't think the version of sprotty we are using supports it.

You should use version 0.6.0.

**Comment by DamianRivas** [comment]
Thank you, is there a guide/changelog somewhere for migrating from pre-0.6.0 sprotty to v0.6.0? And would it be necessary to upgrade the sprotty version on the server as well?

**Comment by spoenemann** [comment]
> Thank you, is there a guide/changelog somewhere for migrating from pre-0.6.0 sprotty to v0.6.0?

No, but feel free to ask questions here, on [Gitter](https://gitter.im/eclipse/sprotty), or on the [forum](https://www.eclipse.org/forums/index.php/f/443/). Many of us are on vacation during summer, though.

> And would it be necessary to upgrade the sprotty version on the server as well?

Yes.

**Comment by DamianRivas** [comment]
Hi, could you explain the changes made to `IDiagramGenerator` and `Traceable`? The Traceable interface doesn't exist anymore in v0.6.0.

`IDiagramGenerator` seems to have undergone significant changes. Comparing `generate`...
```xtend
override generate(Context context) {
		(context.resource.contents.head as StateMachine).toSGraph(context)
}
```
to this
```xtend
	override SModelRoot generate(Resource resource, IDiagramState state, CancelIndicator cancelIndicator) {
		LOG.info("Generating diagram for input: '" + resource.URI.lastSegment + "'")
		
		this.diagramState = state
		this.resource = resource
		
		semantic2diagram = new HashMap
		postProcesses = new ArrayList
		
		val diagram = newSElement(OmlGraph, 'root', null) => [
			layoutOptions = new LayoutOptions [
				HAlign = 'left'
				HGap = 10.0
			]
		]
		
		resource.allContents.forEach[object|
			object.addToDiagram(diagram)
		]
		
		postProcesses.forEach[process|process.apply]

		return diagram
	}
```
... And the way each individual model is generated seemed to change when comparing yang-lsp to theia-xtext-sprotty-example.

Also, what happened to the `IdeLanguageServerExtension`? Does that need to be replaced with something else in v0.6.0 or should we just remove it from the project? I'm not really sure of its purpose (we went off of yang-lsp as an example when building our project).

**Comment by DamianRivas** [comment]
This is the diagram generator we are trying to upgrade: https://github.com/opencaesar/oml/blob/master/io.opencaesar.oml.parent/io.opencaesar.oml.dsl.diagram/src/main/java/io/opencaesar/oml/dsl/diagram/OmlDiagramGenerator.xtend

**Comment by JanKoehnlein** [comment]
Sorry for the late reply due to holiday season. To your questions:

1) `Traceable` has been removed and the trace field has been lifted up to the base class `SModelElement`, so `x instanceof Traceable` becomes `x.trace != null`
2) We've gathered all arguments to `IDiagramGenerator#generate` into a parameter object of type `Context`. This makes it easier to add additional parameters without breaking API in the future. So `diagramState` has become `context.state` etc. You also have access to an `IdCache` which helps to generate  and refer to unique IDs for `SModelElements`
3) To support multiple languages in a common language server, we had to move the LS extensions into a common superclass `DiagramLanguageServer`. Otherwise each `IdeLanguageServerExtension` tried to add the same JSON-RPC method to the `LanguageServerImpl` resulting in a runtime error. So instead of implementing an `IdeLanguageServerExtension` you now bind a `IDiagramServerFactory` for your language. See the https://github.com/TypeFox/theia-xtext-sprotty-example/blob/c2b47191820739b3c3623a90a2668591b0e9cc8f/language-server/io.typefox.examples.theia.states.ide/src/main/java/io/typefox/examples/theia/states/ide/diagram/StatesDiagramServerFactory.xtend#L8 for reference

> And the way each individual model is generated seemed to change when comparing yang-lsp to theia-xtext-sprotty-example.
I don't know what you're referring to. Could you elaborate?

**Comment by DamianRivas** [comment]
Thank you. That's all very helpful. I hope you are enjoying your holiday!

> I don't know what you're referring to. Could you elaborate?

You can ignore that question, I got the hang of it and the backend is now building successfully. We just need to upgrade the frontend to 0.6.0 to test it out.

Right now we are focused on building more features for our IDE so the upgrade to 0.6.0 isn't top priority. I have a different question based on a demo I saw in a YouTube video. There is a demo where you filter the elements rendered in the graph based on what you type in a form that I believe was on the top-right of the window. I could have it wrong, my memory of the demo is vague now so I'll try to find the example again.

How do you make that happen? I'm also interested in implementing a similar feature on the frontend to filter out certain parts of the graph. I understand the architecture of sprotty from your Medium post but how should a developer go about creating their own actions and/or handlers to give our diagrams more interactivity? How do we communicate with sprotty from Theia (or a Theia contribution)?

**Comment by spoenemann** [comment]
Maybe you're referring to http://npm-dependencies.com ? In that stand-alone version the search box in in the bottom, but there is also a Theia integration for it: https://github.com/TypeFox/npm-dependency-graph
Start the browser app, open a project with a package.json, right-click that file and select _Open With_ &rarr; _Dependency Graph_. Then start typing with the graph in focus to get the search box on the top right.

The code for the search box is here:
https://github.com/TypeFox/npm-dependency-graph/blob/master/depgraph-navigator/src/browser/widget/diagram-widget.ts

And the code for filtering is here:
https://github.com/TypeFox/npm-dependency-graph/blob/1b5d20105624833804e57ad791be23c7ca3601f2/depgraph-navigator/src/browser/graph/model-source.ts#L73-L84
https://github.com/TypeFox/npm-dependency-graph/blob/master/depgraph-navigator/src/browser/graph/graph-filter.ts

**Comment by DamianRivas** [comment]
Thank you, Miro. Since all the examples are in v0.6 I should just upgrade to 0.6. Is the Yangster server out of date? I noticed the backend and frontend versions don't match, but you said it's necessary to upgrade the server and the frontend to 0.6 right?

https://github.com/theia-ide/yangster/blob/master/yarn.lock#L8573

https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/gradle/versions.gradle#L6

**Comment by DamianRivas** [comment]
Sorry for the accidental close/reopen.

I'm happy to report that the upgrades were successful. We are now on sprotty and theia `next`. Though I am still wondering about my question above.

Next, I'll try to add the filter widget as we discussed before.

**Comment by JanKoehnlein** [comment]
Sorry, there are lots of questions. Which one are you referring to?

**Comment by DamianRivas** [comment]
Is it necessary for the backend and frontend to have matching sprotty versions? I upgraded our frontend to the latest theia and sprotty and it seems to work perfectly with our server running sprotty v0.4.0

Yangster seems to run similarly:

https://github.com/theia-ide/yangster/blob/master/yarn.lock#L8573

https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/gradle/versions.gradle#L6

**Comment by JanKoehnlein** [comment]
>Is it necessary for the backend and frontend to have matching sprotty versions? I upgraded our frontend to the latest theia and sprotty and it seems to work perfectly with our server running sprotty v0.4.0

ATM, that should be OK. Protocol-wise there have been no changes (accept/dispatch, LSP and  openInTextEditor). Some implementations may have changed on the server so it might behave a bit differently. And there were of course a lot of bugfixes. The biggest diff in the server is that it supports mulitple languages by exposing a single `DiagramLanguageServer` into which languages can plug-in their `DiagramFactories`.

**Comment by DamianRivas** [comment]
Thank you, the server is a bit trickier to upgrade than the front end but I think we are very close. We're having trouble connecting the diagram module. We've narrowed down the problem to this code which we got from the yangster example. There doesn't seem to be a clear place to put this anymore.
```xtend
new OmlIdeSetup {
    override createInjector() {
        Guice.createInjector(Modules2.mixin(new OmlRuntimeModule, new OmlIdeModule, new OmlDiagramModule))
    }
}.createInjectorAndDoEMFRegistration()
```
This isn't a problem in the theia-xtext-sprotty example because you simply edited the generated IdeSteup to include the diagram module. So what about setups that separate them in different packages where the diagram code depends on the Ide code?

We too are interested in keeping the diagram and ide code in separate packages, but the sprotty-server code seems to be defaulting to the `IdeSetup` that's generated by Xtext. We think we've narrowed down the problem to here: https://github.com/eclipse/sprotty-server/blob/master/org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramServerSocketLauncher.xtend#L46

Is there a way to override this in v0.6.0? Or is there a push to keeping the diagram and ide code together?

**Comment by JanKoehnlein** [comment]
I understand: You want to have the diagram code in a separate project that has a dependency on the .ide project correct? Indeed, our standard way is to put the diagram code in the same package as the IDE code, as it is extends the language server with additional functionality.

If you insist on the separation, this should be feasible with a bit of effort. Xtext's language server collects all language setups by looking for service registrations. These are generated by the XtextGenerator when you run the workflow for your language into a file `<yourproject>.ide/src/main/xtext-gen/META-INF/services/org.eclipse.xtext.ISetup`. 
1) You have to suppress the generation of this file (e.g. by using a custom XtextGenerator component in your workflow that overrides `org.eclipse.xtext.xtext.generator.XtextGenerator#generateServices()` or by deleting it after generation (e.g. by adding a line `component = org.eclipse.emf.mwe.utils.DirectoryCleaner { ... }` after the `XtextGenerator` component. 
2) Then provide your own setup file listing your diagram aware setup in `<your diagram project>/src/main/java/META-INF/services/org.eclipse.xtext.ISetup`.

Does that make sense?

**Comment by DamianRivas** [comment]
Thank you, that's correct. I merged the packages and it works great now. We'll continue like this unless we find it necessary to separate them again. So now both the frontend and backend are v0.6.0!

Correct me if I'm wrong, but the filter widget code that Miro shared above seems to be closely tied to a `LocalModelSource` to interact with the graph. How do I translate this to use with a `DiagramServer`? If I want to start simple and just render a `SearchBox` and send its contents to our server, how would I go about doing that? Where in the server would I receive the contents?

**Comment by spoenemann** [comment]
* Create a `FilterAction` both on client and on server.
 * Register the client-side DiagramServer proxy for the action so it's delegated to the server (override `initialize`).
 * Let the server-side DiagramServer handle the action by modifying the `options` map (override `handleAction`).
 * Use the filter options in the DiagramGenerator (you can access them through the `Context`).

**Comment by DamianRivas** [comment]
So the client is dispatching the action to the server successfully, I created and bound a DiagramServer, and it has a handler for the `FilterAction`, but I get an error. It seems to check `ActionTypeAdapter.actionKinds` before it gets to `DefaultDiagramServer.accept()`. Is there an extra step I need to do to add the action to `ActionTypeAdapter.actionKinds`?
```
SEVERE: Unknown action kind: filter
java.lang.IllegalArgumentException: Unknown action kind: filter
	at org.eclipse.sprotty.server.json.ActionTypeAdapter.createInstance(ActionTypeAdapter.java:121)
```
```xtend
class OmlDiagramServer extends LanguageAwareDiagramServer {
	
	override handleAction(Action action) {
		switch(action.getKind()) {
			case FilterAction.KIND: {
				System.out.println("HANDLING ACTION IN OmlDiagramServer")
				handle(action as FilterAction)
			}
		}
		super.handleAction(action)
	}

	def protected handle(FilterAction action) {
		System.out.println("HANDLING FILTER ACTION...")
	}
}
```
```xtend
@Accessors
class FilterAction implements Action {
	public static val KIND = 'filter'
	String kind = KIND
	
	String data
	
	new() {
		System.out.println("FILTER ACTION INSTANTIATED")
	}
}
```

**Comment by DamianRivas** [comment]
I forgot to mention that I did try to add it at `DiagramLanguageServerSetup`, but that didn't seem to work.
```xtend
override configureGson(GsonBuilder gsonBuilder) {
	val factory = new ActionTypeAdapter.Factory()
	factory.addActionKind(FilterAction.KIND, FilterAction)
	gsonBuilder
		.registerTypeAdapterFactory(new ActionTypeAdapter.Factory)
		.registerTypeAdapterFactory(new EnumTypeAdapter.Factory)
}
```

**Comment by DamianRivas** [comment]
Ignore the above! I saw my mistake as I "talked it out" here :)

**Comment by spoenemann** [comment]
`ActionMessage` has a field of type `Action`, which is an interface. Gson doesn't know what class instance to create for a given action unless we configure a custom type adapter.

Your diagram server implementation should be a subclass of `LanguageAwareDiagramServer`, so you can do
```xtend
diagramLanguageServer.diagramUpdater.updateDiagram(this)
```
(Xtend), or
```java
getDiagramLanguageServer().getDiagramUpdater().updateDiagram(this);
```
(Java)

**Comment by DamianRivas** [comment]
Awesome, it's all working now 👍 

Is it possible to connect one edge to another? According to the source code...
> An edge has a source and a target, each of which can be either a node or a port.

So it sounds like it's not currently possible. Our DSL has `relationships` that are represented by edges, but some of these relationships have properties and we'd like another edge to stick out from the original edge to point to a node with its properties.

**Comment by JanKoehnlein** [comment]
The `SEdge` currently only supports one source and one target. In theory, sprotty gives you all the freedom to implement your own hyperedge concept. But I think that's going to be a lot of work untill you get the behavior right.

Instead, I'd propose to add an extra `SNode` to connect the properties edge to. That also gives you all the UI to move this node etc. Its view could be a single point or a small handle.

**Comment by DamianRivas** [comment]
Yeah the extra SNode was what I was thinking but first I wanted to make sure this wasn't doable with native sprotty.

I want to add some graphical editing...

How does the palette popup work in the state machine example? When I hover over existing nodes in my project, it displays the ID of the node so that's working, but that's the only popup functionality that's working.

I implemented the `CodeActionService` since it's clear that's where the `button.id` comes from for the `PaletteButtonView`, but the popup doesn't show up at all.

I tried to follow the graphical-editing branch but it won't build for me locally nor on gitpod so I'm trying to learn from the master branch right now which has some different code.

**Comment by JanKoehnlein** [comment]
> How does the palette popup work in the state machine example?
The menu popup comes from the `CodeActionPopupProvider` that is registered [here](https://github.com/TypeFox/theia-xtext-sprotty-example/blob/c2b47191820739b3c3623a90a2668591b0e9cc8f/theia/states-dsl/src/browser/diagram/states-diagram-configuration.ts#L32). Also mind the consecutive lines. Roughly speaking, the `CAPP` asks the LS for code actions at the text location of the element that is traced by the `SGraph` and creates the repspective menu entries that trigger those code actions.

> I tried to follow the graphical-editing branch but it won't build for me locally nor on gitpod so I'm trying to learn from the master branch right now which has some different code.

Yes, please use master. It turned out that keeping the four branches for the steps up-to-date using rebase is too involving.

**Comment by DamianRivas** [comment]
Ok, and it seems that our CodeActionService is being triggered, but not in the same way that it does in the state machine example.

If I put a breakpoint in here...
```xtend
override getCodeActions(Document document, XtextResource resource, CodeActionParams params, CancelIndicator indicator) {
    var root = resource.contents.head // HERE
    if (root instanceof Terminology)
        createCodeActions(root, params, document)
    else
        emptyList
}
```
it is not triggered when I hover over any part of the page. It only seems to trigger when a trace is done such as when I click on an element in the code that traces to an SModel, or when I click from one SNode to another.

It seems to return the appropriate result: https://i.imgur.com/AmNpiDw.png

...but nothing happens. And my breakpoint in PaletteButtonView isn't triggered. My diagram is configured the same way:
```typescript
container.bind(CodeActionProvider).toSelf().inSingletonScope();
container.bind(IRootPopupModelProvider).to(CodeActionPalettePopupProvider).inSingletonScope();
container.bind(PaletteMouseListener).toSelf().inSingletonScope();
container.rebind(TYPES.PopupMouseListener).to(PaletteMouseListener);
configureModelElement(container, "button:create", PaletteButton, PaletteButtonView);
```

The only difference I can think of is that our diagram is similar to Yangster in that the SGraph that all our elements are contained in is rendered as a visible part of the graph. Whereas in the state machine example, all the elements are just "floating in space" if that makes sense. Would that make a difference in how the popup behaves? Right now, when I hover over the light gray area it simply displays like a URI of the element represented by the SGraph: https://i.imgur.com/21YAvIX.png

**Comment by JanKoehnlein** [comment]
In such situations, I usually try to debug starting from the `ActionDispatcher` to see whether the right actions are coming in. In this case it starts with a `RequestPopupModelAction`.

The delegation to your popup model provider should happen [here](https://github.com/TypeFox/theia-xtext-sprotty-example/blob/c2b47191820739b3c3623a90a2668591b0e9cc8f/theia/states-dsl/src/browser/diagram/states-diagram-configuration.ts#L33).

Did you bind a view for the palette, like [here](https://github.com/TypeFox/theia-xtext-sprotty-example/blob/c2b47191820739b3c3623a90a2668591b0e9cc8f/theia/states-sprotty/src/di.config.ts#L30)?

**Comment by DamianRivas** [comment]
> Did you bind a view for the palette 

Yes: https://github.com/DamianRivas/oml-sprotty/blob/playground/src/di.config.ts#L56

What I'm trying to say is that pop ups _do_ work, but I don't get a palette and it only happens when I hover over a traced element. So I do get a pop up when I hover over any element in the view here: https://i.imgur.com/21YAvIX.png

But as you can see, I just get that light colored box with a URI (the one that says "(Terminology)").

I think I can change that here:
```xtend
protected void handle(RequestPopupModelAction request) {
    SModelRoot model = getModel();
    SModelElement element = SModelIndex.find(model, request.getElementId());
    IPopupModelFactory factory = getPopupModelFactory();
    if (factory != null) {
        SModelRoot popupModel = factory.createPopupModel(element, request, this);
        if (popupModel != null) {
            dispatch(new SetPopupModelAction(popupModel));
        }
    }
}
```
It looks to me like I should be able to bind my own PopupModelFactory and override `createPopupModel`? Is there an example of this? Or let me know if I'm on the wrong track

**Comment by DamianRivas** [comment]
Well, I debugged the state machine example, and I noticed the RequestPopupModelAction doesn't end up in `handleAction` inside `StatesDiagramServer`. So the pop up is not handled by an IPopupModelFactory? How does it end up in `StatesCodeActionService`?

**Comment by JanKoehnlein** [comment]
OK, it's confusing, but he code action popup is started from the client as it just needs the position where to trigger code assist, which it can get from the trace in the SModel, while the element hover is calculated on the server because it needs the AST model. 

Conparing the [diagram config in the example](https://github.com/TypeFox/theia-xtext-sprotty-example/blob/master/theia/states-dsl/src/browser/diagram/states-diagram-configuration.ts) with [yours](https://github.com/DamianRivas/oml-theia/blob/master/io.opencaesar.oml.theia/oml/src/frontend/diagram/di.config.ts) looks like you're lacking a lot of client side bindings.

**Comment by spoenemann** [comment]
To continue the discussion:

 * [create a new issue](https://github.com/eclipse/sprotty/issues/new),
 * [chat on Gitter](https://gitter.im/eclipse/sprotty), or
 * [create a forum thread](https://www.eclipse.org/forums/index.php/f/443/).
